# Generated by Django 5.1.2 on 2024-10-30 17:09

import agency.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='breed',
            field=models.CharField(max_length=50, validators=[agency.models.validate_breed]),
        ),
    ]
